export const types = {
  
    setCurrentUser: '[auth] Set current user',
    setUserAffiliates: '[affiliate] Set user affiliate',
    suppliersAdNew: '[suppliers] Add new supplier',
    suppliersDeleted: '[suppliers] Delete supplier',
    setSuppliers: '[suppliers] Set Suppliers',
    itemsGet: '[items] Get all items',
    itemsGetByCategory: '[items] Get items by category',
    itemsAddNew: '[items] Add new item',
    itemsDeleted: '[items] Delete item',
    brandsGet: '[brands] Get all brands',
    brandsAddNew: '[brands] Add new brand',
    brandsUpdated: '[brands] Update brand',
    brandsDeleted: '[brands] Delete brand',
    categoryAddNew: '[categories] Add new category',
    categoryUpdated: '[categories] Add new category',
    categoryGet: '[categories] Get all categories',
    categoryDeleted: '[categories] Delete category',
    entriesGet: '[entries] Get all entries',
    entriesAddNew: '[entries] Add new entry',
    entriesUpdated: '[entries] Add new entry',
    entriesDeleted: '[entries] Delete entry',
    receiptTypesGet: '[receipt types] Get all receipt types',
    receiptTypesAddNew: '[receipt types] Add new receipt types',
    receiptTypesUpdated: '[receipt types] Update receipt types',
    receiptTypesDeleted: '[receipt types] Delete receipt types',
};
